---
- name: Install Docker
  gather_facts: False
  hosts: all
  #connection: local
  become: true
  vars:
    packages:
       - python3
       - python3-pip
       - python3-setuptools
       - libselinux-python
    pip:
       - six
       - docker
       - requests
  tasks:
  
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker
        state: latest
      become: yes
      
    - name: Install unzip
      package:
        name: unzip
        state: latest
      become: yes  
    
    - name: Create dir /docker
      file:
        path: ./docker/
        state: directory
        
    - name: Downlaoding sqlite files
      get_url:
        url: https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip
        dest: ./docker/sqlite-amalgamation-3260000.zip
        validate_certs: false
      become: yes
      
    - name: Unzip sqllite files
      unarchive:
        src: ./docker/sqlite-amalgamation-3260000.zip
        dest: ./docker
        remote_src: yes
       
    - name: Create yum repo for docker
      ansible.builtin.yum_repository:
        name:  docker-repo
        description: repo 4 docker
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        enabled: yes
        gpgcheck: no
         
    - name: Install pyhton and pip
      package:
        name:  "{{packages}}"
        state: present
        update_cache: true
     
    - name: Install docker sdk
      pip:
        name:  "{{pip}}"
      vars: 
        ansible_python_interpreter: /usr/bin/python3
 
        
    - name: Copy docker file
      copy:
        src: ./dockerfile
        dest: ./docker/dockerfile
        
    - name: start docker
      service:
        name: docker
        state: started 
        daemon_reload: yes

    - name: Build docker image from dockerfile
      vars: 
         ansible_python_interpreter: /usr/bin/python3
      docker_image:
        name: sql
        source: build
        build: 
          path: ./docker
          dockerfile: dockerfile
        state: present 
      
    - name: Run docker container "sql" with "-td"
      shell: docker run -td --name sql sql
      
    - name: Copying sqlite3.so to host VM
      shell: docker cp sql:/app/sqlite3.so ./sqlite3.so
    

