---
- name: Install Docker
  gather_facts: False
  hosts: all
  #connection: local
  become: true
  vars:
    packages:
       - python3
       - python3-pip
       - python3-setuptools
       - libselinux-python
    pip:
       - six
       - docker
       - requests
    #filesfl:
     #  - shell
      # - sqlite3
  tasks:
  
    #- name: yum update
     # yum: 
      # state: latest
       
    #- name: Install yum utils
     # yum:
      #  name: yum-utils
       # state: latest
        
    #- name: yum install epel-release
     # yum:
      # name: epel-release
       #state: latest

    #- name: yum install python-docker-py
     # yum:
      # name: python-docker-py
       #state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker
        state: latest
      become: yes
     
    #- name: downlaod sqlite files
     # get_url:
      #  url: https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip
       # dest: /docker
      #become: yes
    - name: create yum repo 4 docker
      ansible.builtin.yum_repository:
        name:  docker-repo
        description: repo 4 docker
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        enabled: yes
        gpgcheck: no
         
    - name: Install pyhton and pip
      package:
        name:  "{{packages}}"
        state: present
        update_cache: true
     
    - name: Install docker sdk
      pip:
        name:  "{{pip}}"
      vars: 
        ansible_python_interpreter: /usr/bin/python3
 
    - name: create dir
      file:
        path: ./docker/
        state: directory
        
    - name: copy docker file
      copy:
        src: ./dockerfile
        dest: ./docker/dockerfile
        
    - name: copy files fo lib
      copy:
        src: ./shell.c
        dest: ./docker/shell.c
        
    - name: copy sqlite3.c fo lib
      copy:
        src: ./sqlite3.h
        dest: ./docker/sqlite3.h
        
    - name: start docker
      service:
        name: docker
        state: started 
        daemon_reload: yes

    - name: Build docker image from dockerfile
      vars: 
         ansible_python_interpreter: /usr/bin/python3
      docker_image:
        name: sql
        source: build
        build: 
          path: ./docker
          dockerfile: dockerfile
        state: present 
      
       
    - name: Check container
      shell: docker ps -a
      
    - name: docker run -td --name sql sql
      shell: docker run -td --name sql sql
      
    - name: docker cp sql:/app/sqlite3.so /output/sqlite3.so
      shell: docker cp sql:/app/sqlite3.so /output/sqlite3.so
    

