name: “Install docker”
hosts: docker
become: true
vars:
  packages:
     - python3
     - python3-pip
     - python3-setuptools
     - libselinux-python3
   pip: packages:
      - six
      - docker
      - requests
tasks:
- name: “create yum repository for docker”
  ansible.builtin.yum_repository:
    name: docker-repo
    description: “repo for docker”
    baseurl: “https://download.docker.com/linux/centos/7/x86_64/stable/”
    enabled: yes
    gpgcheck: no
name: “Install python and pip”
ansible.builtin.yum:
  name: “{{ packages }}”
  state: present
  update_cache: true


name: “Install docker sdk”
pip:
 name: “{{ pip_packages }}”
vars:
  ansible_python_interpreter: /user/bin/python3


name: “Start docker service”
service:
  name: “docker”
  state: started


name: "Build container"
hosts: build_host
gather_facts: no
become: true
tags: build
vars:
  ansible_python_interpreter: /usr/bin/python3
tasks:
  - name: "find files"
    ansible.builtin.find:
      paths: ~/ansible/Docker/files
      recures: yes
      file_type: "directory"
    delegate_to: 127.0.0.1
    register: files
    become: false 

name: delete old directory
     file:
       path: /root/dockerfiles
       state: absent

name: create build directory 
file:
  path: /root/dockerfiles
  state: directory
  owner: root
  group: root
  mode: ‘0755’

name: “Copy files and build them”
        include tasks: “container_assembly.yml”
        loop: “{{ files.files }}”
